Add a workaround for Next.js production build bug
color-js/color.js pull request #421
Opened 2024-02-10 19:28 UTC by lloydk

Workaround for a Next.js bug when generating a production build of a Next.js project.

Fixes #260

2024-02-10 20:27 UTC, jgerigmeyer approved these changes

2024-02-10 20:30 UTC, MysteryBlokHed approved these changes

2024-02-10 20:36 UTC, LeaVerou requested changes
Can you add a comment that points to the issue so that we don't inadvertently change it in the future?

2024-02-10 21:41 UTC, lloydk commented
> Can you add a comment that points to the issue so that we don't inadvertently change it in the future?

Done

2024-02-11 16:36 UTC, LeaVerou approved these changes
Excellent, thank you!

2024-02-11 16:36 UTC, merged