Add core maintainers to website footer.
color-js/color.js pull request #422
Opened 2024-02-10 20:58 UTC by jgerigmeyer

Closes #414.

I ordered maintainers by date of first commit to the repo.

2024-02-10 21:30 UTC, MysteryBlokHed approved these changes
LGTM

2024-02-10 21:58 UTC, facelessuser approved these changes

2024-02-11 16:33 UTC, svgeesus approved these changes

2024-02-11 16:48 UTC, LeaVerou requested changes
Folks, while I was the one that suggested we invite @lloydk as a co-maintainer (and everyone enthusiastically agreed), this is a discussion that needed to happen *before* we add them to public facing things like these, this cannot be how they find out we’ve invited them 😅

Also, when I opened #414 I was envisioning adding the core maintainers, i.e. those who have been around a while and are also org members. @lloydk definitely has the volume and length of contribution for that, but I think it's still good practice to see how we all work together as a team first, even for a little bit.

2024-02-11 16:48 UTC, LeaVerou commented on _includes/plain.njk
> +	and <a href="https://github.com/lloydk">Lloyd Kupchanko</a>,
```suggestion
	and 
	<a href="https://github.com/MysteryBlokHed">Adam Thompson-Sharpe</a>,
```

2024-02-11 16:51 UTC, LeaVerou approved these changes

2024-02-11 16:51 UTC, merged

2024-02-11 16:51 UTC, LeaVerou commented
Merged, thanks @jgerigmeyer!