Allow any color type when calling individual deltaE functions
color-js/color.js pull request #451
Opened 2024-02-23 23:48 UTC by lloydk

The types for the deltaE functions didn't allow all ColorTypes as parameters. For example, the types didn't allow "red" to be passed as a parameter.

Also, calling a deletaE method with a color such as "red" would cause an exception to be thrown.
```javascript
let x = deltaE2000("red", "white") // Exception thrown
```

2024-02-24 03:23 UTC, MysteryBlokHed reviewed
TypeScript changes LGTM

2024-02-24 19:52 UTC, LeaVerou commented
Agree on solving the problem, not sure about this particular solution, I really don't like the repetition. Can we make this a utility function from `deltaE.js` that these methods import? (with that plus any other commonalities between the functions)

2024-02-24 19:55 UTC, LeaVerou commented
Agree on solving the problem, not sure about this particular solution, I really don't like the repetition. If there are other commonalities between the deltaE functions, we could make this part of a utility function from `deltaE.js` that these methods import.

If there aren't other commonalities, maybe a better solution is to make `getColor()` accept a variable number of arguments so it can become a single line:

```js
let [sample, color] = getColor(sample, color);`
```

2024-02-24 19:56 UTC, LeaVerou requested changes
Agree on solving the problem, not sure about this particular solution, I really don't like the repetition. If there are other commonalities between the deltaE functions, we could make this part of a utility function from `deltaE.js` that these methods import.

If there aren't other commonalities, maybe a better solution is to make `getColor()` accept a variable number of arguments so it can become a single line:

```js
let [sample, color] = getColor(sample, color);`
```

2024-02-24 21:41 UTC, lloydk commented
> Agree on solving the problem, not sure about this particular solution, I really don't like the repetition. If there are other commonalities between the deltaE functions, we could make this part of a utility function from `deltaE.js` that these methods import.
> 

I don't think there are any commonalities between the deltaE functions.

The contrast functions have the same repetition. 

https://github.com/color-js/color.js/blob/1281ad1f6a3da6cea4929d43048d36981003d650/src/contrast/APCA.js#L41-L43


> If there aren't other commonalities, maybe a better solution is to make `getColor()` accept a variable number of arguments so it can become a single line:
> 


What about adding a `getColors` function to `getColor.js`? 
```javascript
export function getColors (...colors) {
	return colors.map(getColor);
}
```

I don't have a strong opinion on any of the solutions:
- keep the repetition
- change `getColor` to take a variable number of arguments
- add a `getColors` function

If we want to make changes to `getColor` or add a `getColors` function I can create a separate PR for that change.

2024-02-24 22:29 UTC, LeaVerou commented
How about this option: instead of variable arguments to `getColor()` we support an array argument. If an array is passed in, an array is returned.

Pros:
- Skips the weird discontinuity at 1 -> 2 args
- Explicit opt in to array handling, possible to handle arrays with even 1 element
- Allows us to add an options object later on

It does add two extra chars to usage, but I think that's an ok tradeoff, and it makes it more explicit.

The advantage of extending `getColor` instead of adding a new function is also that this means `Color.get()` gets this for free.

2024-02-25 04:30 UTC, lloydk commented
> How about this option: instead of variable arguments to `getColor()` we support an array argument. If an array is passed in, an array is returned.
> 
> Pros:
> 
> * Skips the weird discontinuity at 1 -> 2 args
> * Explicit opt in to array handling, possible to handle arrays with even 1 element
> * Allows us to add an options object later on
> 
> It does add two extra chars to usage, but I think that's an ok tradeoff, and it makes it more explicit.
> 
> The advantage of extending `getColor` instead of adding a new function is also that this means `Color.get()` gets this for free.

Created PR #453 for `getColor`. 

When you say `Color.get()` do you mean this function or am I missing something?

https://github.com/color-js/color.js/blob/52d5f69f3fbc25e602ba47a5872f2543c20e194d/src/color.js#L111-L121

2024-02-25 20:10 UTC, LeaVerou commented
> When you say Color.get() do you mean this function or am I missing something?

Ah, I thought it was using `getColor`. We may want to update that too then to keep them in sync.

2024-02-26 03:07 UTC, lloydk commented
Messed up my branch. Hopefully I can fix it without making more of a mess.

2024-02-26 21:39 UTC, jgerigmeyer approved these changes

2024-02-27 04:09 UTC, LeaVerou approved these changes
LGTM!

2024-02-27 04:40 UTC, merged