Fix cam16 and hct type errors
color-js/color.js pull request #622
Opened 2024-12-26 09:26 UTC by lloydk

Add additional types, @ts-expect-error comments and some minor code changes to fix all typescript errors in the cam16 and hct modules.

2024-12-26 17:24 UTC, LeaVerou approved these changes

2024-12-26 17:24 UTC, LeaVerou commented
LGTM though I'm not the best person to review type defs.

2025-01-04 15:52 UTC, MysteryBlokHed requested changes
Just one change and everything else LGTM

2025-01-04 15:52 UTC, MysteryBlokHed commented on src/types.d.ts
> +	dRgbInv: number[];
```suggestion
	dRgb: [number, number, number];
	dRgbInv: [number, number, number];
```

I think these could be narrowed to `[number, number, number]` since they map over a 3-length array:

<https://github.com/color-js/color.js/blob/148af07d1af66f5c9b22d2e50ef5a2eee6a77cc7/src/spaces/cam16.js#L145-L146>

<https://github.com/color-js/color.js/blob/148af07d1af66f5c9b22d2e50ef5a2eee6a77cc7/src/spaces/cam16.js#L175-L180>

2025-01-04 16:16 UTC, lloydk commented on src/types.d.ts
> +	dRgbInv: number[];
done

2025-01-04 16:27 UTC, MysteryBlokHed approved these changes

2025-01-04 17:13 UTC, merged